version: 7.0-Beta-{branch}-{build}
branches:
  only:
  - master
os: Visual Studio 2015
configuration: Release
platform: Win32
before_build:
- appveyor DownloadFile http://cirno.lunar-tokyo.net/PA-Items-%APPVEYOR_REPO_BRANCH%.zip
- 7z x PA-Items-%APPVEYOR_REPO_BRANCH%.zip
- del PA-Items-%APPVEYOR_REPO_BRANCH%.zip
build:
  verbosity: normal
after_build:
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Config\
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Doc\
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Html\
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Meshes\
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Modules\
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Scenarios\
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Script\
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Sound\ -xr!OrbiterSound_SDK
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Textures\
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\NASSP-LICENSE.txt
- 7z a NASSP-V%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\README.md
artifacts:
- path: NASSP-V$(appveyor_build_version).zip
  name: NASSP
deploy:
- provider: GitHub
  tag: NASSP-V$(appveyor_build_version)
  description: V7.0 Beta Release
  auth_token:
    secure: IQ7NMbd0zOFrOgF1Kmp2i5/6C/bTng4X83G4tu9YAoYViKEvjWTPcn7r/0kKJ7M2
  artifact: NASSP
  prerelease: true
